/* Demo data.

   A visitor who has not yet decided whether this tool is worth anything is being asked
   to hand it a reconciliation export of their own tenant to find out. That is the wrong
   order, so a hosted copy can carry a fictional organisation — generated by
   make-demo-set.py, six exports describing the same invented people — and load all of
   it in one click.

   The one thing that must never happen is a reader mistaking it for their own numbers.
   So demo mode is loud: a banner that stays on screen, a mark on the board report that
   prints with it, and a single button that clears everything back out. */
(function (HR) {
  'use strict';

  const U = HR.util, T = (k, p) => HR.i18n.t(k, p);
  const DIR = 'demo/';

  let manifest = undefined;          // undefined = not asked yet, null = not available

  /** Is a demo set published next to this page? Answered once, cached. */
  async function available() {
    if (manifest !== undefined) return manifest;
    manifest = null;
    if (location.protocol === 'file:') return manifest;
    try {
      /* no-store: a CDN in front hands browsers a four-hour TTL on these files, 404s included. */
      const res = await fetch(DIR + 'manifest.json', { cache: 'no-store' });
      if (!res.ok) return manifest;
      const data = await res.json();
      if (data && data.kind === 'helloid-analytics-demo' && Array.isArray(data.files)) {
        manifest = data;
      }
    } catch (e) { /* not published here */ }
    return manifest;
  }

  /**
   * Load every file in the manifest, in the order it lists them: the reconciliation
   * first, because everything else attaches to it.
   */
  async function load() {
    const m = await available();
    if (!m) { U.toast(T('demo.unavailable'), 6000); return false; }
    /* A customer's workspace never gets the fiction: the demo lives in its own. */
    if (HR.workspace && HR.workspace.active().id !== 'demo') {
      if (!HR.workspace.list().some(w => w.id === 'demo')) HR.workspace.create('Demo');
      HR.workspace.switchTo('demo', { pendingDemo: true });
      return false;
    }

    HR.app.state.demo = { generatedOn: m.generatedOn, seed: m.seed, files: m.files.length };
    HR.app.applyChrome();

    /* One batch for the whole set: the files are companions to the same reconciliation,
       so the model is worth building once they are all in rather than once per file. */
    let failed = null;
    await HR.app.batch(async () => {
      for (const entry of m.files) {
        let text;
        try {
          const res = await fetch(DIR + entry.file, { cache: 'no-store' });
          if (!res.ok) throw new Error(res.status + ' ' + res.statusText);
          text = HR.parse.decode(await res.arrayBuffer()).text;
        } catch (e) {
          failed = { file: entry.file, msg: e.message };
          return;
        }
        /* Still awaited one at a time: the vault has to be in place before the rules
           are compared against it. */
        await HR.app.importText(text, 'demo-' + entry.file, { quiet: true });
      }
    });
    if (failed) { U.toast(T('demo.loadFail', failed), 8000); return false; }

    HR.store.saveContext({ demo: HR.app.state.demo });
    HR.usage.action('demo-load');
    U.toast(T('demo.loaded', { n: m.files.length, date: m.generatedOn }), 7000);
    HR.app.go('overview');
    return true;
  }

  /** Leave demo mode by removing the data, not by hiding the banner. */
  async function exit() {
    await HR.store.clear();
    await HR.store.clearContext();
    /* The demo Nedap book lives in config, which the store wipe does not touch. */
    if (HR.config.getNedapBook().demo) HR.config.setNedapBook(HR.nedapons.emptyBook());
    HR.usage.action('demo-exit');
    location.hash = 'sources';
    location.reload();
  }

  /** The banner. Present on every view, and printed on the board report. */
  function banner() {
    const d = HR.app.state.demo;
    if (!d) return null;
    return U.el('div', { class: 'demo-banner' }, [
      U.el('strong', { text: T('demo.badge') }),
      U.el('span', { text: T('demo.explain', { date: d.generatedOn || '—' }) }),
      U.el('button', { class: 'btn sm', text: T('demo.exit'), onclick: exit })
    ]);
  }

  HR.demo = { available, load, exit, banner, isOn: () => !!HR.app.state.demo };
})(window.HR);
